sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build processor-select-columns
script: docker-compose run --rm --entrypoint sh -e KBC_PARAMETER_COLUMNS=id,text -e KBC_DATADIR=/code/Tests/data processor-select-columns /code/Tests/run.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
