version: '2'
services:
  dev:
    image: keboola/processor-select-columns
    tty: true
    stdin_open: true
    volumes:
      - .:/code

  processor-select-columns:
    build: .
    image: keboola/processor-select-columns
    tty: true
    stdin_open: true

  tests:
    image: keboola/processor-select-columns
    tty: true
    stdin_open: true
    volumes:
      - .:/code
    command: php /code/tests/run.php
